# num_samples: 200
num_samples: 1

model:
  x_size: 501
  y_size: 201

physics:
  rho_range: [2000.0, 5000.0]
  vp_range: [2200.0, 5000.0] # км/с
  delimiter_range: [2.0, 3.0]
  multiplicator_range: [1.1, 1.15]

layers:
  # line_func: ragged 
  line_func: perlin
  #line_func: zero 
  num_layers_range: [5,8]
  layer_thickness_range: [0.7, 1.4]

# faults:
#   num_faults_range: [1,2]
#   displacement_range: [20, 40]
#   y_center_range: [50, 150]
#   x_center_range: [100, 400]
#   angle_rad_range: [0.4, 0.6] #в числах пи

anomalies:

  - type: distorted_layer
    line_func: ragged 
    # line_func: perlin
    # line_func: zero 
    num_points: 4
    y_center_range: [120,180]
    x_center_range: [150,350]
    angle_rad_range: [-0.3, 0.3]
  
  # - type: mountain
  #   num_points: 4
  #   y_start: [201]
  #   cx_range: [109, 391]
  #   ry_range: [50, 51]
  #   rx_range: [100, 101]
  
  # - type: ellipse
  #   cy_range: [60, 140]
  #   cx_range: [160, 340]
  #   ry_range: [40,60]
  #   rx_range: [50,160]

  # - type: spline
  #   num_points: 5
  #   cy_range: [70, 130]
  #   cx_range: [200, 300]
  #   ry_range: [50,70]
  #   rx_range: [70,170]